name: Build README

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # Daily at 06:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python build_readme.py
          cat README.md

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git commit -m "Updated content

          Co-authored-by: neemiasbsilva <neemiasbsilva@gmail.com>" || exit 0
          git push
